services:
    mailjet.api.send:
        class: Progrupa\MailjetBundle\Mailjet\Api\Send
        arguments:
            - @mailjet.send_client
            - @mailjet.serializer.serializer
            - %progrupa.mailjet.debug_recipient%

    mailjet.api.factory:
        class: Progrupa\MailjetBundle\Mailjet\Api\Factory
        arguments: [@mailjet.client, @mailjet.serializer.serializer]

    mailjet.client:
        class: GuzzleHttp\Client
        arguments:
            options:
                base_uri: 'https://api.mailjet.com/v3/REST/'
                auth: ['d355fa1dc93774e2691498bfdc400d84', '5279bdc6e1538db5f51337b8329d88ca']
                headers: {Content-Type: 'application/json'}

    mailjet.send_client:
        class: GuzzleHttp\Client
        arguments:
            options:
                base_uri: 'https://api.mailjet.com/v3/'
                auth: ['d355fa1dc93774e2691498bfdc400d84', '5279bdc6e1538db5f51337b8329d88ca']
                headers: {Content-Type: 'application/json'}
